# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroupImagesTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!



  # Pods for GroupImagesTest

  target 'GroupImagesTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GroupImagesTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SDWebImage', '~> 4.4.0'

end
